---
version: '3.7'

networks:
  default:
    external:
      name: ksd

services:
  superset:
    build: .
    container_name: superset
    ports:
      - 28088:8088
    environment:
      WTF_CSRF_ENABLED: "False"
